def possible_file_input_error_message() -> None:
    print("You need to create a custom input file\n"
          "You can create a specific maze or use this one:\n"
          "WIDTH=15\n"
          "HEIGHT=15\n"
          "ENTRY=0,0\n"
          "EXIT=5,9\n"
          "OUTPUT_FILE=input\n"
          "PERFECT=False\n"
          "SEED=None\n"
          "ALGORITHM=None\n"
          "DISPLAY_MODE=None\n"
          "DISPLAY_SOLUTION=TRUE\n"
          "STYLE=None\n"
          "WALL_COLOR=None\n"
          "TUNNEL_COLOR=None\n"
          "ENTRY_COLOR=None\n"
          "EXIT_COLOR=None\n"
          "LOGO_COLOR=None\n"
          "SOLUTION_COLOR=None\n")
