import sys


def possible_file_input_error_message() -> None:
    print(
        'You need to create a custom input file: config.txt\n'
        'Copy paste this below to create the file :\n\n'
        'cat << EOF > config.txt\n'
        'WIDTH=15\n'
        'HEIGHT=15\n'
        'ENTRY=0,0\n'
        'EXIT=5,9\n'
        'OUTPUT_FILE=output.txt\n'
        'PERFECT=False\n'
        'SEED=None\n'
        '#Possible display : large or thin\n'
        'DISPLAY_MODE=None\n'
        'DISPLAY_SOLUTION=TRUE\n'
        '#Possible Style options :\n'
        '#- 0 for RESET\n'
        '#- 1 for BOLD\n'
        '#- 2 for DIM\n'
        '#- 3 for ITALIC\n'
        '#- 4 for UNDERLINED\n'
        '#- 5 for SLOW_BLINKING\n'
        '#- 6 for FAST_BLINKING\n'
        '#- 7 for REVERSE\n'
        '#- 8 for HIDDEN\n'
        '#- 9 for STRIKETROUGH\n'
        'STYLE=None\n'
        '#Possible color (wall/others) options :\n'
        '#- 30/40 for Black\n'
        '#- 31/41 for Red\n'
        '#- 32/42 for Gree\n'
        '#- 33/43 for Yellow\n'
        '#- 34/44 for Blue\n'
        '#- 35/45 for Magenta\n'
        '#- 36/46 for Cyan\n'
        '#- 37/47 for White\n'
        'WALL_COLOR=None\n'
        'TUNNEL_COLOR=None\n'
        'ENTRY_COLOR=None\n'
        'EXIT_COLOR=None\n'
        'LOGO_COLOR=None\n'
        'SOLUTION_COLOR=None\n'
        'EOF\n',
        file=sys.stderr
    )
